name: All-Clean

on:
  # 手动触发
  workflow_dispatch:
  # 定时触发 (北京时间每周四 23:00---UTC周四时间 15:00)
  schedule:
    - cron: '0 15 * * 4'

jobs:
  Cleaning:
    runs-on: ubuntu-22.04

    steps:
    - name: Delete Old Workflows
      uses: Mattraks/delete-workflow-runs@main
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        retain_days: 2
        keep_minimum_runs: 0

    - name: Delete Old Releases
      uses: dev-drprasad/delete-older-releases@master
      with:
        keep_latest: 8
        delete_tags: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
