name: Trigger Build for OpenWrt Branch

on:
  push:
    branches: [ openwrt ]
    paths:
      - 'configs/**'
      - 'scripts/**'
      - '.github/workflows/**'
  workflow_dispatch:
    inputs:
      package_profile:
        description: '选择软件包版本'
        required: true
        default: 'Pro'
        type: choice
        options:
        - Pro
        - Max
        - Ultra

jobs:
  build:
    uses: ./.github/workflows/build.yml
    with:
      branch_config: 'openwrt_base'
      package_config: ${{ inputs.package_profile || 'Pro' }}
      target_arch: 'ipq60xx'
