# .github/workflows/trigger-openwrt.yml
name: 为 ImmortalWrt 分支触发构建

on:
  push:
    branches: [ immwrt ]
    paths:
      - 'configs/**'
      - 'scripts/**'
      - '.github/workflows/**'
  workflow_dispatch:
    inputs:
      ubuntu_version:
        description: '选择运行环境操作系统版本'
        required: true
        default: 'ubuntu-22.04'
        type: choice
        options:
        - ubuntu-22.04
        - ubuntu-24.04
        - ubuntu-latest
      target_arch:
        description: '选择芯片架构'
        required: true
        default: 'ipq60xx'
        type: choice
        options:
        - ipq60xx
        - ipq80xx
      package_profile:
        description: '选择软件包版本'
        required: true
        default: 'Pro'
        type: choice
        options:
        - Pro
        - Max
        - Ultra

jobs:
  build:
    uses: ./.github/workflows/build.yml
    with:
      ubuntu_version: ${{ inputs.ubuntu_version }}
      # 【关键修改】使用新的配置文件名
      branch_config: 'base_immwrt'
      target_arch: ${{ inputs.target_arch || 'ipq60xx' }}
      package_config: ${{ inputs.package_profile || 'Pro' }}
