# .github/workflows/weekly-build.yml
name: 每周自动构建

on:
  schedule:
    - cron: '0 16 * * 4'
  workflow_dispatch:

jobs:
  # 【关键修改】第一阶段：并行编译所有分支的 Ultra 配置
  build-ultra:
    strategy:
      fail-fast: false
      max-parallel: 3 # 【关键修改】设置最大并行数
      matrix:
        branch_config: [openwrt_base, immwrt_base, libwrt_base]
    uses: ./.github/workflows/build.yml
    with:
      ubuntu_version: 'ubuntu-22.04'
      branch_config: ${{ matrix.branch_config }}
      package_config: 'Ultra'
      target_arch: 'ipq60xx'

  # 【关键修改】第二阶段：等待 Ultra 完成后，并行编译所有分支的 Max 配置
  build-max:
    needs: build-ultra # 【关键修改】依赖第一阶段
    strategy:
      fail-fast: false
      max-parallel: 3 # 【关键修改】设置最大并行数
      matrix:
        branch_config: [openwrt_base, immwrt_base, libwrt_base]
    uses: ./.github/workflows/build.yml
    with:
      ubuntu_version: 'ubuntu-22.04'
      branch_config: ${{ matrix.branch_config }}
      package_config: 'Max'
      target_arch: 'ipq60xx'

  # 【关键修改】第三阶段：等待 Max 完成后，并行编译所有分支的 Pro 配置
  build-pro:
    needs: build-max # 【关键修改】依赖第二阶段
    strategy:
      fail-fast: false
      max-parallel: 3 # 【关键修改】设置最大并行数
      matrix:
        branch_config: [openwrt_base, immwrt_base, libwrt_base]
    uses: ./.github/workflows/build.yml
    with:
      ubuntu_version: 'ubuntu-22.04'
      branch_config: ${{ matrix.branch_config }}
      package_config: 'Pro'
      target_arch: 'ipq60xx'
